[misc]
devMode = false
autoSwitchLanguage = true
checkModPackTranslationUpdate = true
[resourcePack]
autoDownloadVMTranslationPack = false
autoLoadExtraTranslationPack = true
resourcePackIndex = "DEFAULT"
extraPackName = "Enigmatic Skies Chinese Translation"
extraPackCustomIndex = 0
[modInstallCheck]
i18nUpdateMod = true
vaultPatcher = false
textureLocaleRedirector = false
